# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.3

EAPI="3"
SUPPORT_PYTHON_ABIS="1"
DISTUTILS_SRC_TEST="setup.py"

inherit distutils


DESCRIPTION="Easily download, build, install, upgrade, and uninstall Python packages"
HOMEPAGE="http://packages.python.org/distribute"
SRC_URI="http://pypi.python.org/packages/source/d/distribute/${P}.tar.gz"

LICENSE="ZPL"
KEYWORDS="~x86"
SLOT="0"
IUSE="doc"

DEPEND="dev-python/setuptools"
RDEPEND="${DEPEND}"


src_install() {
	distutils_src_install
	if use doc; then
		dodoc -r docs
	fi
}
